spring:
  application:
    name: bl1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://pg:5432/studs
    url: jdbc:postgresql://localhost:10109/studs
    username: s288870
    password: qta730
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none


server:
  port: 10550
  shutdown: graceful
  servlet:
    context-path: /api/v1

jwt:
  secret: 'secretKeY123'
